# Generated by Django 4.2 on 2023-04-19 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
